apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "console.fullname" . }}
  labels:
    {{- include "console.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.console.replicaCount }}
  {{- with .Values.console.strategy }}
  strategy:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "console.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        {{- with .Values.console.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        {{- include "console.selectorLabels" . | nindent 8 }}
        {{- with .Values.console.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "console.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.console.podSecurityContext | nindent 8 }}
      containers:
      - name: {{ include "console.name" . }}
        securityContext:
          {{- toYaml .Values.console.securityContext | nindent 10 }}
        image: "{{ .Values.console.image.repository }}:{{ .Values.console.image.tag | default .Values.image.tag }}"
        imagePullPolicy: {{ .Values.console.image.pullPolicy }}
        ports:
        - name: http
          containerPort: {{ .Values.console.service.targetPort }}
          protocol: TCP
        - name: http-metrics
          containerPort: {{ .Values.console.service.metricsPort }}
          protocol: TCP
        {{- with .Values.console.env }}
        env:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        {{- with .Values.console.envFrom }}
        envFrom:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        resources:
          {{- toYaml .Values.console.resources | nindent 10 }}
      {{- with .Values.console.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.console.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.console.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
