apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "flyteconsole.configMapName" . }}
  namespace: {{ template "flyte.namespace" . }}
  labels: {{ include "flyteconsole.labels" . | nindent 4 }}
data: {{ toYaml .Values.flyte.configmap.console | nindent 2 }}
