{{- if .Values.userclouds.enabled -}}
{{- range .Values.userclouds.externalSecrets }}
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .name }}
  labels:
    {{- include "userclouds.labels" $ | nindent 4 }}
spec:
  refreshInterval: {{ .refreshInterval | default "1h" }}
  secretStoreRef:
    name: {{ .secretStoreRef.name }}
    kind: {{ .secretStoreRef.kind | default "ClusterSecretStore" }}
  target:
    name: {{ .name }}
    creationPolicy: Owner
  data:
    {{- range .data }}
    - secretKey: {{ .secretKey }}
      remoteRef:
        key: {{ .remoteRef.key }}
        {{- if .remoteRef.property }}
        property: {{ .remoteRef.property }}
        {{- end }}
    {{- end }}
{{- end }}
{{- end }}
