{{- if and .Values.userclouds.enabled .Values.userclouds.autoscaling.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "userclouds.fullname" . }}
  labels:
    {{- include "userclouds.labels" . | nindent 4 }}
    app.kubernetes.io/component: all
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "userclouds.fullname" . }}
  minReplicas: {{ .Values.userclouds.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.userclouds.autoscaling.maxReplicas }}
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.userclouds.autoscaling.targetCPUUtilizationPercentage }}
    {{- if .Values.userclouds.autoscaling.targetMemoryUtilizationPercentage }}
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ .Values.userclouds.autoscaling.targetMemoryUtilizationPercentage }}
    {{- end }}
{{- end }}
