{{- if and .Values.userclouds.enabled .Values.userclouds.serviceAccount.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "userclouds.fullname" . }}-secrets-reader
  labels:
    {{- include "userclouds.labels" . | nindent 4 }}
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "list", "watch", "create", "update", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "userclouds.fullname" . }}-secrets-reader
  labels:
    {{- include "userclouds.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "userclouds.fullname" . }}-secrets-reader
subjects:
  - kind: ServiceAccount
    name: {{ include "userclouds.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
{{- end }}
