{{- if and .Values.userclouds.enabled .Values.userclouds.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "userclouds.serviceAccountName" . }}
  labels:
    {{- include "userclouds.labels" . | nindent 4 }}
  {{- with .Values.userclouds.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
