{{- if and .Values.global.usercloudsEnabled .Values.userclouds.metrics.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "userclouds.fullname" . }}
  labels:
    {{- include "userclouds.labels" . | nindent 4 }}
    {{- with .Values.userclouds.metrics.serviceMonitor.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  selector:
    matchLabels:
      {{- include "userclouds.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: all
  endpoints:
    - port: http
      interval: {{ .Values.userclouds.metrics.serviceMonitor.interval }}
      scrapeTimeout: {{ .Values.userclouds.metrics.serviceMonitor.scrapeTimeout }}
      path: /metrics
      {{- with .Values.userclouds.metrics.serviceMonitor.metricRelabelings }}
      metricRelabelings:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.userclouds.metrics.serviceMonitor.relabelings }}
      relabelings:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
