{{- if .Values.global.usercloudsEnabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "userclouds.fullname" . }}
  labels:
    {{- include "userclouds.labels" . | nindent 4 }}
    app.kubernetes.io/component: all
spec:
  type: {{ .Values.userclouds.service.type }}
  ports:
    - port: {{ .Values.userclouds.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "userclouds.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: all
{{- end }}
