controlplane:
  enabled: true
global:
  replicaCount: 1 # Keeping low replica count for testing purposes.
  image:
    repository: 440744229819.dkr.ecr.us-east-2.amazonaws.com/cloud # only for testing
    pullPolicy: Always # Will be changed once iteration is done.
    tag: 5851360e4ba391b6bef72c333e497d1cac5b7c9d # Will be changed once iteration is done.
  imagePullSecrets:
  nameOverride: ""
  fullnameOverride: ""
  serviceAccount:
    create: true
    annotations: {}
  podAnnotations:
    linkerd.io/inject: disabled
    prometheus.io/path: /metrics
    prometheus.io/port: "10254"
  service:
    type: ClusterIP
    grpcport: 80
    httpport: 81
    debugport: 82
    connectport: 83
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 250m
      memory: 250Mi
  env:
    - name: GOMEMLIMIT
      valueFrom:
        resourceFieldRef:
          resource: limits.memory
    - name: GOMAXPROCS
      valueFrom:
        resourceFieldRef:
          resource: limits.cpu
  autoscaling:
    enabled: true
    minReplicas: 1
    maxReplicas: 1 # again keeping this for testing and would be changed.
    targetCPUUtilizationPercentage: 80
    targetMemoryUtilizationPercentage: 80
  secrets: {}
  podMonitor:
    custom:
      enabled: false
      metricRelabelings: []
  probe:
    enabled: false
  serviceProfile:
    enabled: false
  spreadConstraints:
    enabled: false
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  argo:
    enabled: false
  externalSecrets:
    refreshInterval: 1h
    refs: {}
  postgres-exporter:
    enabled: false
    fullnameOverride: postgres-exporter
    serviceMonitor:
      enabled: false
      labels:
        instance: union
  configMap:
    cache:
      identity:
        enabled: false
    sharedService:
      connectPort: 8081
    authorizer:
      type: "Noop"
      internalCommunicationConfig:
        enabled: false
    connection:
      environment: staging
      region: us-east-2
      rootTenantURLPattern: dns:///{{ organization }}.cloud-staging.union.ai
    otel:
      type: otlpgrpc
      otlpgrpc:
        endpoint: http://otel-collector.monitoring.svc.cluster.local:4317
      sampler:
        parentSampler: traceid
        traceIdRatio: 0.001
    union:
      internalConnectionConfig:
        enabled: true
        urlPattern: "{{ service }}.union.svc.cluster.local:80"
      connection:
        trustedIdentityClaims:
          externalIdentityClaim: 0oa2n55xystvEjmOD5d7
      auth:
        enable: false
    logger:
      level: 6

services:
  artifacts:
    fullnameOverride: "artifacts"
    initContainers:
      - name: migrate
        args:
          - artifacts
          - migrate
          - --config
          - "/etc/config/*.yaml"
    args:
      - artifacts
      - serve
      - --config
      - /etc/config/*.yaml
    configMap:
      sharedService:
        metrics:
          scope: "artifacts:"
      db:
        host: "database-1-instance-1.c982kkq6ghd1.us-east-2.rds.amazonaws.com"
        username: "postgres"
        passwordPath: /etc/secrets/db-pass.txt
        connectionPool:
          maxIdleConnections: 20
          maxOpenConnections: 20
          maxConnectionLifetime: 1m
      artifactsConfig:
        app:
          adminClient:
            hackFlagUntilCellIsolation: true
          artifactBlobStoreConfig:
            container: artifacts-offloaded-byocp-test-us-east-2
            stow:
              config:
                auth_type: iam
                region: us-east-2
              kind: s3
            type: stow
          artifactDatabaseConfig:
            connMaxLifeTime: 1m
            maxIdleConnections: 20
            maxOpenConnections: 30
            postgres:
              dbname: postgres
              host: database-1-instance-1.c982kkq6ghd1.us-east-2.rds.amazonaws.com
              options: sslmode=disable
              passwordPath: /etc/secrets/db-pass.txt
              port: 5432
              readReplicaHost: database-1-instance-1.c982kkq6ghd1.us-east-2.rds.amazonaws.com
              username: postgres
          artifactServerConfig:
            httpPort: 8089
            port: 8080
            respectUserOrgsForServerless: true
          artifactTriggerConfig:
            executionMaxRetryCount: 3
            executionSchedulerQuerySize: 20
            executionSchedulers: 1
            executionSchedulersWait: 10
            triggerProcessorQuerySize: 100
            triggerProcessors: 1
            triggerProcessorsWait: 10
  authorizer:
    fullnameOverride: "authorizer"
    args:
      - authorizer
      - serve
      - --config
      - /etc/config/*.yaml
    configMap:
      sharedService:
        metrics:
          scope: "authorizer:"
  cluster:
    fullnameOverride: "cluster"
    args:
      - cloudcluster
      - serve
      - --config
      - /etc/config/*.yaml
    configMap:
      sharedService:
        metrics:
          scope: "cluster:"
      timeseries:
        timestream:
          databaseName: "byocp-test-timestream-db"
          tableName: "cloudMetricsRaw"
          derivedTableName: "cloudMetricsDerived"
          region: "us-east-2"
          tags:
            - environment: "staging"
      db:
        host: "database-1-instance-1.c982kkq6ghd1.us-east-2.rds.amazonaws.com"
        username: "postgres"
        passwordPath: /etc/secrets/db-pass.txt
        connectionPool:
          maxIdleConnections: 20
          maxOpenConnections: 20
          maxConnectionLifetime: 1m
      cluster:
        cloudflare:
          active: false
  dataproxy:
    fullnameOverride: "dataproxy"
    args:
      - dataproxy
      - serve
      - --config
      - /etc/config/*.yaml
    configMap:
      sharedService:
        metrics:
          scope: "usage:"
  executions:
    fullnameOverride: "executions"
    args:
      - cloudpropeller
      - serve
      - --config
      - /etc/config/*.yaml
    serviceAccount:
      annotations:
        eks.amazonaws.com/role-arn: arn:aws:iam::440744229819:role/staging-executions-role
    configMap:
      sharedService:
        metrics:
          scope: "executions:"
      db:
        host: "database-1-instance-1.c982kkq6ghd1.us-east-2.rds.amazonaws.com"
        username: "postgres"
        passwordPath: /etc/secrets/db-pass.txt
        connectionPool:
          maxIdleConnections: 20
          maxOpenConnections: 20
          maxConnectionLifetime: 1m
      cloudEventsProcessor:
        cloudProvider: AWS
        region: us-east-2
        subscriber:
          accountId: "440744229819"
          queueName: staging-us-east-2-executions-cloudEventsQueue
      executions:
        app:
          adminClient:
            connection:
              authorizationHeader: flyte-authorization
              clientId: 0oa2n55xystvEjmOD5d7
              scopes:
                - all
          taskValidation:
            serverlessTaskPodSpecValidation:
              enabled: "true"
            skipOrgs: utt-mgdp-stg-us-east-2,utt-mgdp-stg-us-west-2,hosted
        apps:
          enrichIdentities: true
          publicURLPattern: https://%s.apps.%s.cloud-staging.union.ai
  identity:
    fullnameOverride: "identity"
    args:
      - cloudidentity
      - serve
      - --config
      - /etc/config/*.yaml
    configMap:
      sharedService:
        metrics:
          scope: "identity:"
      identity:
        app:
          rootTenantURLPattern: dns:///{{ organization }}.cloud-staging.union.ai
          env: staging
          identityProviderConfig:
            okta:
              clientRegistrationEndpointUrl: https://unionai.oktapreview.com
          adminClient:
            connection:
              clientId: 0oa2n55xystvEjmOD5d7
              authorizationHeader: "flyte-authorization"
              scopes:
                - all
  usage:
    fullnameOverride: "usage"
    args:
      - usage
      - serve
      - --config
      - /etc/config/*.yaml
    serviceAccount:
      annotations:
        eks.amazonaws.com/role-arn: arn:aws:iam::440744229819:role/staging-usage-usageRole
    configMap:
      sharedService:
        metrics:
          scope: "usage:"
      cloudProvider:
        awsConfig:
          region: us-east-2
        provider: aws
      timeseries:
        timestream:
          databaseName: staging-timestream
          derivedTableName: cloudMetricsDerived
          query:
            enabled: true
            includeQuotaBasedResourceMetrics: true
          tableName: cloudMetricsRaw
          tags:
            - environment: staging
