# ============================================================================
# Union Control Plane Configuration for AWS
# ============================================================================
# This file provides a production-ready template for deploying Union control
# plane on AWS EKS. Replace the placeholder values below with your actual
# configuration.
#
# For more details, see: https://docs.union.ai/deployment/
# ============================================================================

# ----------------------------------------------------------------------------
# Configuration Variables to Replace
# ----------------------------------------------------------------------------
# Configure the global variables below for your AWS deployment.
# These values override the defaults in values.yaml and provide AWS-specific
# configuration (RDS endpoints, S3 buckets, IAM roles, etc.).
#
# Note: For intra-cluster deployments, additional variables are defined in
# values.aws.selfhosted-intracluster.yaml
# ----------------------------------------------------------------------------

# ----------------------------------------------------------------------------
# SECTION 1: AWS-Specific Global Configuration
# ----------------------------------------------------------------------------
# Override global values from values.yaml with AWS-specific settings.

global:

  # IAM role ARN for artifacts service (IRSA)
  # Leave empty if artifacts service is disabled
  # Example: "arn:aws:iam::123456789012:role/union-artifacts-role"
  ARTIFACT_IAM_ROLE_ARN: ""

  # IAM role ARN for Flyte services (IRSA)
  # Example: "arn:aws:iam::123456789012:role/union-flyteadmin-role"
  # Note: Used by flyteadmin, datacatalog, and cacheservice
  FLYTEADMIN_IAM_ROLE_ARN: ""

# ----------------------------------------------------------------------------
# SECTION 2: AWS Specific Role configuration
# ----------------------------------------------------------------------------
# Override service-specific settings as needed.

services:
  artifacts:
    serviceAccount:
      annotations:
        eks.amazonaws.com/role-arn: "{{ .Values.global.ARTIFACT_IAM_ROLE_ARN }}"

flyte:
  flyteadmin:
    serviceAccount:
      annotations:
        eks.amazonaws.com/role-arn: "{{ .Values.global.FLYTEADMIN_IAM_ROLE_ARN }}"

  datacatalog:
    serviceAccount:
      annotations:
        eks.amazonaws.com/role-arn: "{{ .Values.global.FLYTEADMIN_IAM_ROLE_ARN }}"

  cacheservice:
    serviceAccount:
      annotations:
        eks.amazonaws.com/role-arn: "{{ .Values.global.FLYTEADMIN_IAM_ROLE_ARN }}"