{{- if .Values.uvolMountBroker.enabled }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: union-uvol-broker
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "uvolBroker.labels" . | nindent 4 }}
data:
  broker.yaml: |
    uvolBroker:
      driverName: {{ .Values.uvolMountBroker.driverName }}
      kubeletDir: {{ .Values.uvolMountBroker.kubeletDir }}
      socketDir: {{ .Values.uvolMountBroker.socketDir }}
      stateDir: {{ .Values.uvolMountBroker.stateDir }}
      {{- if .Values.uvolMountBroker.nodeCache.enabled }}
      nodeCacheDir: {{ required "uvolMountBroker.nodeCache.hostPath is required when nodeCache is enabled" .Values.uvolMountBroker.nodeCache.hostPath }}
      {{- end }}
      metricsScope: "{{ .Values.uvolMountBroker.metricsScope }}"
      profilerPort: {{ .Values.uvolMountBroker.profilerPort }}
      {{- with .Values.uvolMountBroker.config }}
      {{- tpl (toYaml .) $ | nindent 6 }}
      {{- end }}
{{- end }}
