push-hook = false
ship-strategy = "api"

[branches]
main = "main"
perennials = ["mike/monitoring-testing-wip"]

[hosting]
platform = "github"

[lineage]
"mike/prometheus-refactor" = "main"
"mike/controlplane-monitoring" = "mike/prometheus-refactor"
