{{- if eq (include "dcgmExporter.enabled" .) "true" }}
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: dcgm-exporter
  namespace: kube-system
  labels:
    {{- include "dcgmExporter.labels" . | nindent 4 }}
    app.kubernetes.io/component: "dcgm-exporter"
spec:
  updateStrategy:
    type: RollingUpdate
  selector:
    matchLabels:
      {{- include "dcgmExporter.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: "dcgm-exporter"
  template:
    metadata:
      {{- with  .Values.dcgmExporter.podAnnotations }}
      annotations:
      {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "dcgmExporter.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: "dcgm-exporter"
    spec:
      priorityClassName: {{ .Values.dcgmExporter.priorityClassName | default "system-node-critical" }}
      {{- if .Values.hostNetwork }}
      hostNetwork: {{ .Values.dcgmExporter.hostNetwork }}
      dnsPolicy: ClusterFirstWithHostNet
      {{- end }}
      {{- with .Values.dcgmExporter.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "dcgmExporter.serviceAccountName" . }}
      {{- with .Values.dcgmExporter.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - name: "pod-gpu-resources"
          hostPath:
            path: {{ .Values.dcgmExporter.kubeletPath }}
        {{- range .Values.dcgmExporter.extraHostVolumes }}
        - name: {{ .name | quote }}
          hostPath:
            path: {{ .hostPath | quote }}
        {{- end }}
        - name: dcgm-exporter
          configMap:
            name: dcgm-exporter-metrics
      containers:
        - name: exporter
          image: "{{ .Values.image.dcgmExporter.repository }}:{{ .Values.image.dcgmExporter.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.dcgmExporter.pullPolicy }}
          {{- with .Values.dcgmExporter.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          args:
            - "-f"
            - "/etc/dcgm-exporter/metrics.csv"
          env:
            - name: "DCGM_EXPORTER_KUBERNETES"
              value: "true"
            - name: "DCGM_EXPORTER_LISTEN"
              value: ":{{ .Values.dcgmExporter.service.port }}"
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          {{- with .Values.dcgmExporter.extraEnv }}
          {{- toYaml . | nindent 12 }}
          {{- end }}
          ports:
            - name: "metrics"
              containerPort: {{ .Values.dcgmExporter.service.port }}
          volumeMounts:
            - name: "pod-gpu-resources"
              readOnly: true
              mountPath: "/var/lib/kubelet/pod-resources"
            - name: "dcgm-exporter"
              mountPath: "/etc/dcgm-exporter"
          {{- with .Values.dcgmExporter.extraVolumeMounts }}
          {{- toYaml . | nindent 12 }}
          {{- end }}
          livenessProbe:
            httpGet:
              path: /health
              port: {{ .Values.dcgmExporter.service.port }}
            initialDelaySeconds: 45
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: /health
              port: {{ .Values.dcgmExporter.service.port }}
            initialDelaySeconds: 45
          resources:
            {{- toYaml .Values.dcgmExporter.resources | nindent 12 }}
      {{- with .Values.dcgmExporter.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      affinity:
        {{- include "dcgmExporter.affinity" . | nindent 8 }}
      {{- with .Values.dcgmExporter.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
