{{- if .Values.dcgmExporter.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: dcgm-exporter
  namespace: kube-system
  labels:
    {{- include "dcgmExporter.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 9400
      targetPort: 9400
      protocol: TCP
      name: "metrics"
  selector:
    {{- include "dcgmExporter.selectorLabels" . | nindent 4 }}
{{- end }}