{{- if .Values.dcgmExporter.enabled -}}
{{- if .Values.dcgmExporter.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "dcgmExporter.serviceAccountName" . }}
  namespace: kube-system
  labels:
    {{- include "dcgmExporter.labels" . | nindent 4 }}
  {{- with .Values.dcgmExporter.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- end }}
{{- end }}