{{- if eq (include "dcgmExporter.enabled" .) "true" }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: dcgm-exporter
  namespace: kube-system
  labels:
    {{- include "dcgmExporter.labels" . | nindent 4 }}
    app.kubernetes.io/component: "dcgm-exporter"
spec:
  selector:
    matchLabels:
      {{- include "dcgmExporter.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: "dcgm-exporter"
  namespaceSelector:
    matchNames:
      - kube-system
  endpoints:
    - port: "metrics"
      path: "/metrics"
{{- end }}

