{{- if eq (include "dcgmExporter.enabled" .) "true" }}
apiVersion: v1
kind: Service
metadata:
  name: dcgm-exporter
  namespace: kube-system
  labels:
    {{- include "dcgmExporter.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.dcgmExporter.service.port }}
      targetPort: {{ .Values.dcgmExporter.service.port }}
      protocol: TCP
      name: "metrics"
  selector:
    {{- include "dcgmExporter.selectorLabels" . | nindent 4 }}
{{- end }}