{{- if eq (include "secrets.admin.shouldCreate" .) "true" }}
{{- $secret := .Values.secrets.admin.clientSecret | required ".Values.secrets.admin.clientSecret is required when admin client credentials has been enabled." -}}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "secrets.admin.secretName" . }}
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  app_secret: {{ $secret | b64enc | toString }}
  client_secret: {{ $secret | b64enc | toString }}
{{- end }}
