{{- if include "operator.enableDepot" . }}
apiVersion: v1
kind: Secret
metadata:
  name: depot-token
  namespace: {{ .Release.Namespace }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ printf `{"auths":{}}` | b64enc }}
{{- end }}
