{{- if and (eq (include "secrets.eagerClientCreds.enabled" .) "true") (not .Values.secrets.eagerClientCreds.existingSecret.name) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "secrets.eagerClientCreds.secretName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "secrets.managedObjectLabels" . | nindent 4 }}
  {{- with .Values.secrets.commonAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
type: Opaque
data:
  {{ include "secrets.eagerClientCreds.clientIdKey" . }}: {{ .Values.secrets.eagerClientCreds.clientId | b64enc }}
  {{ include "secrets.eagerClientCreds.clientSecretKey" . }}: {{ .Values.secrets.eagerClientCreds.clientSecret | b64enc }}
{{- end }}
