{{- if and (eq (include "secrets.eagerApiKey.enabled" .) "true") (not .Values.secrets.eagerApiKey.existingSecret.name) }}
{{- $ref := include "secrets.eagerApiKey.secretRef" . | fromYaml -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $ref.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "secrets.managedObjectLabels" . | nindent 4 }}
  {{- with .Values.secrets.commonAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
type: Opaque
data:
  {{ $ref.key }}: {{ .Values.secrets.eagerApiKey.value | b64enc }}
{{- end }}
