{{- if and (eq (include "secrets.imageBuilder.pull.enabled" .) "true") (not .Values.secrets.imageBuilder.pull.existingSecret.name) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "secrets.imageBuilder.pull.secretName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    union.ai/secret-type: image-builder-pull
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ .Values.secrets.imageBuilder.pull.dockerconfigjson | b64enc }}
{{- end }}
