{{- if and (eq (include "secrets.imageBuilder.push.enabled" .) "true") (not .Values.secrets.imageBuilder.push.existingSecret.name) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "secrets.imageBuilder.push.secretName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "secrets.managedObjectLabels" . | nindent 4 }}
  {{- with .Values.secrets.commonAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
type: Opaque
data:
{{- range $k, $v := .Values.secrets.imageBuilder.push.values }}
  {{ $k }}: {{ $v | b64enc }}
{{- end }}
{{- end }}
