{{- if .Values.ingress.enabled }}
{{- if .Values.serving.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "unionai-dataplane.fullname" . }}-serving
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ include "unionai-dataplane.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  {{- with .Values.ingress.serving.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- with .Values.ingress.serving.class }}
  ingressClassName: {{ . | quote }}
  {{- end }}
  {{- with .Values.ingress.serving.tls }}
  tls:
    {{ toYaml . | nindent 4 }}
  {{- end }}
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: kourier-internal
            port:
              number: 80
    {{- with include "ingress.serving.host" . }}
    host: {{ . }}
    {{- end }}
{{- end }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "unionai-dataplane.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ include "unionai-dataplane.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  {{- with .Values.ingress.dataproxy.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- with .Values.ingress.dataproxy.class }}
  ingressClassName: {{ . | quote }}
  {{- end }}
  {{- with .Values.ingress.dataproxy.tls }}
  tls:
    {{ toYaml . | nindent 4 }}
  {{- end }}
  rules:
    - http:
        paths:
          - path: /api/v1/dataproxy/
            pathType: Prefix
            backend:
              service:
                name: union-operator-proxy
                port:
                  number: 8080
          - path: /prometheus/
            pathType: Prefix
            backend:
              service:
                name: union-operator-prometheus
                port:
                  number: 80
          - path: /clickhouse/
            pathType: Prefix
            backend:
              service:
                name: union-operator-proxy
                port:
                  number: 8080
          - path: /dataplane/
            pathType: Prefix
            backend:
              service:
                name: union-operator-proxy
                port:
                  number: 8080
          - path: /resourcequota/v1/project_quota
            pathType: Prefix
            backend:
              service:
                name: union-operator-proxy
                port:
                  number: 8080
          - path: /spark-history-server/
            pathType: Prefix
            backend:
              service:
                name: union-operator-proxy
                port:
                  number: 8080
          - path: /secrets/api/v1
            pathType: Prefix
            backend:
              service:
                name: union-operator-proxy
                port:
                  number: 8080
          - path: /data_plane_object_store/api/v1/
            pathType: Prefix
            backend:
              service:
                name: union-operator-proxy
                port:
                  number: 8080
          - path: /cloudidl.actor.ActorEnvironmentService/
            pathType: ImplementationSpecific
            backend:
              service:
                name: union-operator-proxy
                port:
                  number: 8080
          - path: /cloudidl.logs.dataplane.LogsService/
            pathType: ImplementationSpecific
            backend:
              service:
                name: union-operator-proxy
                port:
                  number: 8080
          - path: /cloudidl.objectstore.v1.ObjectStoreService/
            pathType: ImplementationSpecific
            backend:
              service:
                name: union-operator-proxy
                port:
                  number: 8080
          - path: /cloudidl.imagebuilder.dataplane.ImageService/
            pathType: ImplementationSpecific
            backend:
              service:
                name: union-operator-proxy
                port:
                  number: 8080
    {{- with include "ingress.dataproxy.host" . }}
      host: {{ . }}
    {{- end }}
{{- end }}
