{{- if and (eq (include "secrets.internalCaCert.enabled" .) "true") (not .Values.secrets.internalCaCert.existingSecret.name) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "secrets.internalCaCert.secretName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "secrets.managedObjectLabels" . | nindent 4 }}
  {{- with .Values.secrets.commonAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
type: Opaque
data:
  {{ include "secrets.internalCaCert.caCertKey" . }}: {{ .Values.secrets.internalCaCert.value | b64enc }}
{{- end }}
