{{- if and (eq (include "secrets.internalCaCert.enabled" .) "true") (not .Values.secrets.internalCaCert.existingSecret.name) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "secrets.internalCaCert.secretName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    union.ai/secret-type: internal-ca-cert
type: Opaque
data:
  {{ include "secrets.internalCaCert.caCertKey" . }}: {{ .Values.secrets.internalCaCert.value | b64enc }}
{{- end }}
