{{- if include "useCommonServiceAccount" . }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "common.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  annotations:
    {{- include "global.serviceAccountAnnotations" . | nindent 4 }}
    {{- with .Values.commonServiceAccount.annotations }}
    {{- tpl (toYaml .) $ | nindent 4 }}
    {{- end }}
{{- end }}
