{{- if or (include "singleNamespace" .) (include "operator.enableDepot" .) .Values.taskPodTemplate.nodeSelector .Values.taskPodTemplate.affinity .Values.taskPodTemplate.tolerations }}
apiVersion: v1
kind: PodTemplate
metadata:
  name: task-template
  namespace: {{ .Release.Namespace }}
template:
  spec:
{{- if include "singleNamespace" . }}
    serviceAccountName: union
{{- end }}
{{- if include "operator.enableDepot" . }}
    imagePullSecrets:
      - name: depot-token
{{- end }}
    containers:
      - name: default
        image: docker.io/rwgrim/docker-noop
{{- with .Values.taskPodTemplate.workingDir }}
        workingDir: {{ . | quote }}
{{- end }}
{{- with .Values.taskPodTemplate.nodeSelector }}
    nodeSelector:
      {{- toYaml . | nindent 6 }}
{{- end }}
{{- with .Values.taskPodTemplate.affinity }}
    affinity:
      {{- toYaml . | nindent 6 }}
{{- end }}
{{- with .Values.taskPodTemplate.tolerations }}
    tolerations:
      {{- toYaml . | nindent 6 }}
{{- end }}
{{- end }}
