{{- $imageBuilderPullEnabled := eq (include "secrets.imageBuilder.pull.enabled" .) "true" }}
{{- if or (include "singleNamespace" .) (include "operator.enableDepot" .) $imageBuilderPullEnabled }}
apiVersion: v1
kind: PodTemplate
metadata:
  name: task-template
  namespace: {{ .Release.Namespace }}
template:
  spec:
{{- if include "singleNamespace" . }}
    serviceAccountName: union
{{- end }}
{{- if $imageBuilderPullEnabled }}
    imagePullSecrets:
      - name: {{ include "secrets.imageBuilder.pull.secretName" . }}
{{- else if include "operator.enableDepot" . }}
    imagePullSecrets:
      - name: depot-token
{{- end }}
    containers:
      - name: default
        image: docker.io/rwgrim/docker-noop
{{- end }}
