{{- if include "singleNamespace" . }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: union
  namespace: {{ .Release.Namespace }}
  annotations:
    {{ tpl .Values.userRoleAnnotationKey . }}: {{ tpl .Values.userRoleAnnotationValue . }}
automountServiceAccountToken: true
{{- end }}