{{- if and .Values.imageBuilder.enabled (include "singleNamespace" .) }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.imageBuilder.targetConfigMapName }}
  labels:
    {{- include "operator.labels" . | nindent 4 }}
data:
  storage.yaml: | {{ tpl (include "storage" .) $ | nindent 4 }}
{{- if or .Values.imageBuilder.buildkitUri .Values.imageBuilder.buildkit.enabled }}
  buildkit-uri: {{ (include "imagebuilder.buildkit.uri" .) | quote }}
{{- else }}
  buildkit-uri: ""
{{- end }}
  default-repository: {{ include "imagebuilder.defaultRepository" . | quote }}
  authentication-type: {{ include "imagebuilder.authenticationType" . | quote }}
{{- end }}
