{{- define "imagebuilder.buildkit.hpa" -}}
{{- if and (include "imagebuilder.buildkit.enabled" .) .Values.imageBuilder.buildkit.autoscaling.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "imagebuilder.buildkit.workloadName" . }}
  labels:
    {{- include "imagebuilder.buildkit.workloadLabels" . | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "imagebuilder.buildkit.workloadName" . }}
  minReplicas: {{ .Values.imageBuilder.buildkit.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.imageBuilder.buildkit.autoscaling.maxReplicas }}
  metrics:
    {{- if .Values.imageBuilder.buildkit.autoscaling.targetCPUUtilizationPercentage }}
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.imageBuilder.buildkit.autoscaling.targetCPUUtilizationPercentage }}
    {{- end }}
    {{- if .Values.imageBuilder.buildkit.autoscaling.targetMemoryUtilizationPercentage }}
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ .Values.imageBuilder.buildkit.autoscaling.targetMemoryUtilizationPercentage }}
    {{- end }}
{{- end }}
{{- end -}}

{{- include "imagebuilder.buildkit.hpa" . }}
{{- if and (include "imagebuilder.buildkit.enabled" .) (.Values.imageBuilder.buildkit.arm | default dict).enabled }}
{{- $arm := include "imagebuilder.buildkit.hpa" (merge (dict "buildkitArm" true) .) }}
{{- if $arm }}
---
{{ $arm }}
{{- end }}
{{- end }}
