{{- if and (include "imagebuilder.buildkit.enabled" .) (gt (.Values.imageBuilder.buildkit.replicaCount | int) 1) }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  labels:
    {{- include "imagebuilder.buildkit.labels" . | nindent 4 }}
  name: {{ include "imagebuilder.buildkit.fullname" . }}
spec:
  selector:
    matchLabels:
      {{- include "imagebuilder.buildkit.selectorLabels" . | nindent 6 }}
  minAvailable: {{ .Values.imageBuilder.buildkit.pdb.minAvailable }}
{{- end }}
