{{- if and (include "imagebuilder.buildkit.enabled" .) .Values.imageBuilder.buildkit.openShift.enabled }}
{{- include "openshift.sccRbac" (dict "root" . "name" (include "imagebuilder.buildkit.openShiftSccName" .) "labels" (include "imagebuilder.buildkit.labels" .) "serviceAccountName" (include "buildkit.serviceAccountName" .)) }}
{{- end }}
