{{- if and (include "imagebuilder.buildkit.enabled" .) .Values.imageBuilder.buildkit.openShift.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "imagebuilder.buildkit.openShiftSccName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "imagebuilder.buildkit.labels" . | nindent 4 }}
rules:
  - apiGroups:
      - security.openshift.io
    resources:
      - securitycontextconstraints
    resourceNames:
      - {{ include "imagebuilder.buildkit.openShiftSccName" . }}
    verbs:
      - use
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "imagebuilder.buildkit.openShiftSccName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "imagebuilder.buildkit.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "imagebuilder.buildkit.openShiftSccName" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "buildkit.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
{{- end }}
