{{- if and (include "imagebuilder.buildkit.enabled" .) .Values.imageBuilder.buildkit.openShift.enabled .Values.imageBuilder.buildkit.openShift.securityContextConstraints.create }}
apiVersion: security.openshift.io/v1
kind: SecurityContextConstraints
metadata:
  name: {{ include "imagebuilder.buildkit.openShiftSccName" . }}
  labels:
    {{- include "imagebuilder.buildkit.labels" . | nindent 4 }}
allowHostDirVolumePlugin: false
allowHostIPC: false
allowHostNetwork: false
allowHostPID: false
allowHostPorts: false
allowPrivilegeEscalation: {{ .Values.imageBuilder.buildkit.openShift.securityContextConstraints.allowPrivilegeEscalation }}
allowPrivilegedContainer: false
allowedCapabilities: []
defaultAllowPrivilegeEscalation: {{ .Values.imageBuilder.buildkit.openShift.securityContextConstraints.defaultAllowPrivilegeEscalation }}
forbiddenSysctls:
  - "*"
readOnlyRootFilesystem: false
requiredDropCapabilities: []
runAsUser:
  type: MustRunAs
  uid: 1000
seLinuxContext:
  type: MustRunAs
seccompProfiles:
  - unconfined
  - runtime/default
fsGroup:
  type: RunAsAny
supplementalGroups:
  type: RunAsAny
volumes:
  - configMap
  - downwardAPI
  - emptyDir
  - projected
  - secret
{{- end }}
