{{- if and (include "imagebuilder.buildkit.enabled" .) (not (include "useCommonServiceAccount" .)) (index .Values.imageBuilder.buildkit.serviceAccount "create" | default true) }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "buildkit.serviceAccountName" . }}
  annotations:
    {{- include "buildkit.serviceAccount.annotations" . | nindent 4 }}
{{ if .Values.imageBuilder.buildkit.serviceAccount.imagePullSecret }}
imagePullSecrets:
  - name: {{ .Values.imageBuilder.buildkit.serviceAccount.imagePullSecret }}
{{- end }}
{{- end }}