{{- if (include "imagebuilder.buildkit.enabled" .) }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "imagebuilder.buildkit.fullname" . }}
  labels:
    {{- include "imagebuilder.buildkit.labels" . | nindent 4 }}
  {{- with .Values.imageBuilder.buildkit.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.imageBuilder.buildkit.service.type }}
  {{- if .Values.imageBuilder.buildkit.service.loadbalancerIp }}
  loadBalancerIP: {{ .Values.imageBuilder.buildkit.service.loadbalancerIp | quote }}
  {{- end }}
  ports:
    - port: {{ .Values.imageBuilder.buildkit.service.port }}
      targetPort: tcp
      protocol: TCP
      name: tcp
  selector:
    {{- include "imagebuilder.buildkit.selectorLabels" . | nindent 4 }}
{{- end }}