{{- if and (include "imagebuilder.buildkit.enabled" .) (index .Values.imageBuilder.buildkit.serviceAccount "create" | default true) }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.imageBuilder.buildkit.serviceAccount.name }}
  {{- with .Values.imageBuilder.buildkit.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}