{{/* Validate database name configuration */}}
{{- include "controlplane.validateDatabaseNames" . }}

{{- if (index .Values "controlplane" | default dict).enabled }}
{{- range $serviceKey, $serviceConfig := .Values.services }}
---
{{- $service := dict "config" $serviceConfig "key" $serviceKey "Release" $.Release "Values" $.Values "Chart" $.Chart }}
{{- if not $service.config.disabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "unionai.fullname" $service }}
  labels:
    {{- include "unionai.labels" $service | nindent 4 }}
data:
  config.yaml: |
    {{- include "unionai.configMap" $service | nindent 4 }}
---
{{- end }}
{{- end }}
{{- end }}

