{{- /* Union-specific flyteadmin config (private.yaml) - not supported by upstream flyte-core chart */}}
{{- with .Values.flyte.configmap.adminServer.private }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: flyte-admin-private-config
  namespace: {{ template "flyte.namespace" $ }}
  labels: {{ include "flyteadmin.labels" $ | nindent 4 }}
data:
  private.yaml: |
    {{- tpl (toYaml .) $ | nindent 4 }}
{{- end }}
