---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: flyteadmin
  namespace: {{ template "flyte.namespace" . }}
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: flyteadmin
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: datacatalog
  namespace: {{ template "flyte.namespace" . }}
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: datacatalog
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: cacheservice
  namespace: {{ template "flyte.namespace" . }}
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: cacheservice
