{{- if .Values.global.probe.enabled }}
kind: Probe
apiVersion: monitoring.coreos.com/v1
metadata:
  name: {{ include "unionai.fullname" . }}-probe-http
  labels:
    {{- include "unionai.labels" . | nindent 4 }}
    instance: union
spec:
  interval: 60s
  jobName: 'integrations/blackbox/service'
  module: http_2xx
  prober:
    url: blackbox.kube-prometheus-stack.svc.cluster.local:9115
    path: /probe
  targets:
    staticConfig:
      static:
      - {{ .Values.probe.url }}
{{- end}}
