{{- if (index .Values "controlplane" | default dict).enabled }}
{{- range $serviceKey, $serviceConfig := .Values.services }}
---
{{- $service := dict "config" $serviceConfig "key" $serviceKey "Release" $.Release "Values" $.Values "Chart" $.Chart}}
{{- if and (not $service.config.disabled) $service.config.secrets }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "unionai.fullname" $service }}
  labels:
    {{- include "unionai.labels" $service | nindent 4 }}
type: Opaque
stringData:
  {{- with $service.config.secrets }}
  {{ toYaml . | nindent 4 }}
  {{- end }}
  {{- end }}
{{- end }}
{{- end }}

