{{- range $serviceKey, $serviceConfig := .Values.services }}
{{- $service := dict "config" $serviceConfig "key" $serviceKey "Release" $.Release "Values" $.Values "Chart" $.Chart}}
{{- if not $service.config.disabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "unionai.fullname" $service }}
  labels:
    {{- include "unionai.labels" $service | nindent 4 }}
type: Opaque
stringData:
  {{- with $service.config.secrets }}
  {{ toYaml . | nindent 4 }}
  {{- end }}
  {{- end }}   {{/* closes the `if not disabled` */}}
{{- end }}     {{/* closes the `range` */}}

