{{- if (index .Values "controlplane" | default dict).enabled }}
{{- range $serviceKey, $serviceConfig := .Values.services }}
---
{{- $service := dict "config" $serviceConfig "key" $serviceKey "Release" $.Release "Values" $.Values "Chart" $.Chart}}
{{- if not $service.config.disabled }}
{{- if eq (include "unionai.serviceAccount.create" $service | trim) "true" }}
{{- $annotations := include "unionai.serviceAccount.annotations" $service | fromYaml }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "unionai.serviceAccountName" $service }}
  labels:
    {{- include "unionai.labels" $service | nindent 4 }}
  {{- with $annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}
