{{- if and (index .Values "controlplane" | default dict).enabled .Values.actions.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "actions.fullname" . }}
  namespace: {{ include "actions.namespace" . }}
  labels:
    {{- include "actions.labels" . | nindent 4 }}
data:
  config.yaml: |
    {{- include "actions.configMap" . | nindent 4 }}
{{- end }}
