{{- if and .Values.cost.enabled (.Capabilities.APIVersions.Has "monitoring.coreos.com/v1") -}}
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: union-opencost-rules
  namespace: {{ .Release.Namespace }}
  labels:
    release: {{ .Release.Name }}
    platform.union.ai/prometheus-group: union-features
spec:
  {{ include "cost.recording-rules" . | nindent 2 }}
{{- end }}
