{{- if .Values.unionoperatorMonitoring.enabled -}}
{{- if .Values.unionoperatorMonitoring.prometheus.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "unionoperatorMonitoring.prometheus.serviceAccountName" . }}
  labels:
    {{- include "unionoperatorMonitoring.prometheus.labels" . | nindent 4 }}
  {{- with .Values.unionoperatorMonitoring.prometheus.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
{{- end }}
