{{- if .Values.scylla.enabled }}
{{- if .Values.scylla.storageClass.create }}
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ .Values.scylla.storageClass.name | default "scylladb" }}
  {{- with .Values.scylla.storageClass.labels }}
  labels:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.scylla.storageClass.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- with .Values.scylla.storageClass.allowedTopologies }}
allowedTopologies: {{ . }}
{{- end }}
provisioner: {{ .Values.scylla.storageClass.provisioner | default "ebs.csi.eks.amazonaws.com" }}
volumeBindingMode: {{ .Values.scylla.storageClass.volumeBindingMode | default "WaitForFirstConsumer" }}
{{- with .Values.scylla.storageClass.parameters }}
parameters:
  {{- toYaml . | nindent 2 }}
{{- end }}
reclaimPolicy: {{ .Values.scylla.storageClass.reclaimPolicy | default "Delete" }}
allowVolumeExpansion: {{ .Values.scylla.storageClass.allowVolumeExpansion | default true }}
{{- end }}
{{- end }}
