{{- if and .Values.proxy.secretManager.enabled (eq .Values.proxy.secretManager.type "K8s") }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "proxy.serviceAccountName" . }}-secret
  namespace: {{ include "proxy.secretsNamespace" . }}
  labels:
    {{- include "proxy.labels" . | nindent 4 }}
rules:
  - apiGroups:
      - '*'
    resources:
      - secrets
    verbs:
      - get
      - list
      - create
      - update
      - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "proxy.serviceAccountName" . }}-secret
  namespace: {{ include "proxy.secretsNamespace" . }}
  labels:
    {{- include "proxy.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "proxy.serviceAccountName" . }}-secret
subjects:
  - kind: ServiceAccount
    name: {{ include "proxy.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
{{- end }}
