apiVersion: v1
kind: Service
metadata:
  name: {{ include "union-operator.fullname" . }}
  labels:
    {{- include "operator.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: debug
      protocol: TCP
      name: debug
  selector:
    {{- include "operator.selectorLabels" . | nindent 4 }}
