{{- define "control-plane-library.flyteadmin" }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ template "flyteadmin.name" . }}
  namespace: {{ template "flyte.namespace" . }}
  labels: {{ include "flyteadmin.labels" . | nindent 4 }}
rules:
  - apiGroups:
      - ""
      - flyte.lyft.com
      - rbac.authorization.k8s.io
    resources:
      - configmaps
      - flyteworkflows
      - namespaces
      - pods
      - resourcequotas
      - roles
      - rolebindings
      - secrets
      - services
      - serviceaccounts
      - spark-role
    verbs:
      - '*'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ template "flyteadmin.name" . }}-binding
  namespace: {{ template "flyte.namespace" . }}
  labels: {{ include "flyteadmin.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ template "flyteadmin.name" . }}
subjects:
  - kind: ServiceAccount
    name: {{ template "flyteadmin.name" . }}
    namespace: {{ template "flyte.namespace" . }}
{{- end }}
