{{- if not .Values.database.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "onebox.dbSecretName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "onebox.labels" . | nindent 4 }}
type: Opaque
stringData:
  password: {{ .Values.database.password | quote }}
{{- end }}
