image:
  repository: alpine/kubectl
  tag: "1.33.4"
  pullPolicy: IfNotPresent

labels: {}

annotations: {}

knativeServingName: union-operator-serving

adoption:
  enabled: false
  targetRelease: ""
  targetNamespace: ""

job:
  backoffLimit: 3
  activeDeadlineSeconds: 900
  ttlSecondsAfterFinished: 300

resources:
  requests:
    cpu: 10m
    memory: 32Mi
  limits:
    cpu: 500m
    memory: 128Mi

nodeSelector: {}
tolerations: []
affinity: {}

nameOverride: ""
fullnameOverride: ""
