{{- if and (or (eq ((index .Values "services" "authorizer" "configMap" "authorizer" "type") | default "") "Union") (eq ((index .Values "services" "authorizer" "configMap" "authorizer" "type") | default "") "UserClouds")) .Values.union.authz.pdb.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "union.authz.fullname" . }}
  labels:
    {{- include "union.authz.labels" . | nindent 4 }}
spec:
  {{- if .Values.union.authz.pdb.minAvailable }}
  minAvailable: {{ .Values.union.authz.pdb.minAvailable }}
  {{- end }}
  {{- if .Values.union.authz.pdb.maxUnavailable }}
  maxUnavailable: {{ .Values.union.authz.pdb.maxUnavailable }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "union.authz.selectorLabels" . | nindent 6 }}
{{- end }}
