{{- if and (.Values.union.authz.enabled) .Values.union.authz.serviceAccount.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "union.authz.fullname" . }}-secrets-manager
  labels:
    {{- include "union.authz.labels" . | nindent 4 }}
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "list", "watch", "create", "update", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "union.authz.fullname" . }}-secrets-manager
  labels:
    {{- include "union.authz.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "union.authz.fullname" . }}-secrets-manager
subjects:
  - kind: ServiceAccount
    name: {{ include "union.authz.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
{{- end }}
