{{- if and .Values.union.authz.enabled .Values.union.authz.metrics.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "union.authz.fullname" . }}
  labels:
    {{- include "union.authz.labels" . | nindent 4 }}
    {{- with .Values.union.authz.metrics.serviceMonitor.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  selector:
    matchLabels:
      {{- include "union.authz.selectorLabels" . | nindent 6 }}
  endpoints:
    - port: http
      interval: {{ .Values.union.authz.metrics.serviceMonitor.interval }}
      scrapeTimeout: {{ .Values.union.authz.metrics.serviceMonitor.scrapeTimeout }}
      path: /metrics
      {{- with .Values.union.authz.metrics.serviceMonitor.metricRelabelings }}
      metricRelabelings:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.union.authz.metrics.serviceMonitor.relabelings }}
      relabelings:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
