{{- if eq ((index .Values "services" "authorizer" "configMap" "authorizer" "type") | default "") "UserClouds" -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "union.authz.fullname" . }}
  labels:
    {{- include "union.authz.labels" . | nindent 4 }}
spec:
  type: {{ .Values.union.authz.service.type }}
  ports:
    - port: {{ .Values.union.authz.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "union.authz.selectorLabels" . | nindent 4 }}
{{- end }}
