{{- if .Values.eventExporter.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "union-operator.fullname" . }}-event-exporter
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "unionai-dataplane.labels" . | nindent 4 }}
    app.kubernetes.io/component: event-exporter
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "{{ .Values.eventExporter.metricsPort }}"
    prometheus.io/path: "/metrics"
spec:
  selector:
    app.kubernetes.io/component: event-exporter
    {{- include "unionai-dataplane.selectorLabels" . | nindent 4 }}
  ports:
    - name: metrics
      port: {{ .Values.eventExporter.metricsPort }}
      targetPort: metrics
      protocol: TCP
  type: ClusterIP
{{- end }}
