apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: flytepropeller
  namespace: {{ .Release.Namespace }}
  labels:
    release: {{ .Release.Name }}
spec:
  selector:
    matchLabels:
      platform.union.ai/service-group: {{ .Release.Name }}
  namespaceSelector:
    matchNames:
      - "{{ .Release.Namespace }}"
  endpoints:
    - port: "debug"
      path: "/metrics"
---
{{- if .Values.opencost.enabled -}}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: opencost
  namespace: {{ .Release.Namespace }}
  labels:
    release: {{ .Release.Name }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Values.opencost.fullnameOverride }}
  namespaceSelector:
    matchNames:
      - "{{ .Release.Namespace }}"
  endpoints:
    - port: http # This should match the name of the port in your OpenCost service
      interval: 1m # Adjust scrape interval as needed
      path: /metrics # The metrics endpoint path for OpenCost
{{- end }}
