{{- if .Values.cost.enabled -}}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ .Values.cost.serviceMonitor.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    release: {{ .Release.Name }}
spec:
  selector:
    {{- with .Values.cost.serviceMonitor.matchLabels }}
    matchLabels:
    {{- toYaml . | nindent 6 }}
    {{- end }}
  namespaceSelector:
    matchNames:
      - "{{ .Release.Namespace }}"
  endpoints:
    - port: http
      interval: 1m
      path: /metrics
      honorLabels: true
      metricRelabelings:
        - sourceLabels: [ "__name__" ]
          separator: ";"
          regex: "kube_node_labels|kube_pod_labels|node_total_hourly_cost|node_ram_hourly_cost|node_cpu_hourly_cost|node_gpu_hourly_cost"
          action: keep
{{- end }}
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: union-service-monitor
  namespace: {{ .Release.Namespace }}
  labels:
    release: {{ .Release.Name }}
spec:
  selector:
    matchLabels:
      platform.union.ai/service-group: {{ .Release.Name }}
  namespaceSelector:
    matchNames:
      - "{{ .Release.Namespace }}"
  endpoints:
    - port: debug
      interval: 1m
      path: /metrics
      honorLabels: true
