{{- define "control-plane-library.gateway" }}
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: {{ template "flyte.name" . }}
  namespace: {{ template "flyte.namespace" . }}
spec:
  gatewayClassName: {{ .Values.envoyGateway.gatewayClassName }}
  listeners:
    - name: https
      protocol: HTTPS
      port: 443
      hostname: {{ .Values.global.UNION_HOST | quote }}
      tls:
        mode: Terminate
        certificateRefs:
          - kind: Secret
            namespace: {{ .Values.global.TLS_SECRET_NAMESPACE }}
            name: {{ .Values.global.TLS_SECRET_NAME }}
    {{- if .Values.flyte.common.ingress.isServerless }}
    - name: https-serverless
      protocol: HTTPS
      port: 443
      hostname: {{ .Values.flyte.common.ingress.serverlessVanityHost | quote }}
      tls:
        mode: Terminate
        certificateRefs:
          - kind: Secret
            namespace: {{ .Values.global.TLS_SECRET_NAMESPACE }}
            name: {{ .Values.global.TLS_SECRET_NAME }}
    {{- end }}
    {{- $intraHost := .Values.global.CONTROLPLANE_INTRA_CLUSTER_HOST }}
    {{- $internalTlsSecret := .Values.global.INTERNAL_TLS_SECRET_NAME | default .Values.global.TLS_SECRET_NAME }}
    {{- if and $intraHost (ne $intraHost .Values.global.UNION_HOST) }}
    - name: https-intracluster
      protocol: HTTPS
      port: 443
      hostname: {{ $intraHost | quote }}
      tls:
        mode: Terminate
        certificateRefs:
          - kind: Secret
            namespace: {{ .Values.global.TLS_SECRET_NAMESPACE }}
            name: {{ $internalTlsSecret }}
    {{- end }}
    {{- $ingressFqdn := include "controlPlaneLibrary.ingressFqdn" . }}
    {{- if and $ingressFqdn (ne $ingressFqdn .Values.global.UNION_HOST) (ne $ingressFqdn $intraHost) }}
    - name: https-local
      protocol: HTTPS
      port: 443
      hostname: {{ $ingressFqdn | quote }}
      tls:
        mode: Terminate
        certificateRefs:
          - kind: Secret
            namespace: {{ .Values.global.TLS_SECRET_NAMESPACE }}
            name: {{ $internalTlsSecret }}
    {{- end }}
{{- end }}
