{{- if .Values.acceleratedDatasets.enabled }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: union-nodeobserver
  namespace: {{ .Release.Namespace }}
data:
  {{- with .Values.acceleratedDatasets.config }}
  config.yaml: | {{ tpl (toYaml .) $ | nindent 4 }}
    {{- end }}
{{- end }}
