apiVersion: v1
kind: Service
metadata:
  name: minio
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: minio
    app.kubernetes.io/instance: sandbox
spec:
  type: ClusterIP
  ports:
    - name: minio
      port: 9000
      protocol: TCP
      targetPort: minio
    - name: minio-console
      port: 9001
      protocol: TCP
      targetPort: minio-console
  selector:
    app.kubernetes.io/name: minio
    app.kubernetes.io/instance: union-sandbox
