{{- if .Values.fluentbit.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "fluentbit.configMapName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
      {{- include "fluent-bit.labels" . | nindent 4 }}
data:
  custom_parsers.conf: |
      {{- (tpl .Values.fluentbit.config.customParsers $) | nindent 4 }}
  fluent-bit.conf: |
      {{- $service := include "fluentbit.service" . }}
      {{- if $service }}
        {{- $service | nindent 4 }}
      {{- end }}
      {{- $inputs := include "fluentbit.inputs" . }}
      {{- if $inputs }}
        {{- $inputs | nindent 4 }}
      {{- end }}
      {{- $filters := include "fluentbit.filters" . }}
      {{- if $filters }}
        {{- $filters | nindent 4 }}
      {{- end }}
      {{- $outputs := include "fluentbit.outputs" . }}
      {{- if $outputs }}
        {{- $outputs | nindent 4 }}
      {{- end }}
    {{- range $key, $val := .Values.fluentbit.config.upstream }}
    {{ $key }}: |
      {{- (tpl $val $) | nindent 4 }}
    {{- end }}
    {{- range $key, $val := .Values.fluentbit.config.extraFiles }}
    {{ $key }}: |
      {{- (tpl $val $) | nindent 4 }}
    {{- end }}
{{- end }}
