{{- if .Values.fluentbit.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "fluentbit.configMapName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
      {{- include "fluent-bit.labels" . | nindent 4 }}
data:
  custom_parsers.conf: |
      {{- (tpl .Values.fluentbit.config.customParsers $) | nindent 4 }}
  fluent-bit.conf: |
      {{- with include "fluentbit.service" . }}
        {{ . | nindent 4 }}
      {{- end }}
      {{- with include "fluentbit.inputs" . }}
        {{ . | nindent 4 }}
      {{- end }}
      {{- with include "fluentbit.filters" . }}
        {{ . | nindent 4 }}
      {{- end }}
      {{- with include "fluentbit.outputs" . }}
        {{ . | nindent 4 }}
      {{- end }}
    {{- range $key, $val := .Values.fluentbit.config.upstream }}
    {{ $key }}: |
      {{- (tpl $val $) | nindent 4 }}
    {{- end }}
    {{- range $key, $val := .Values.fluentbit.config.extraFiles }}
    {{ $key }}: |
      {{- (tpl $val $) | nindent 4 }}
    {{- end }}
{{- end }}
