{{- if .Values.fluentbit.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "fluentbit.configMapName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
      {{- include "fluentbit.labels" . | nindent 4 }}
data:
  custom_parsers.conf: |
      {{- $parsers := include "fluentbit.customParsers" . }}
      {{- if $parsers }}
        {{- $parsers | nindent 4 }}
      {{- end }}
  fluent-bit.conf: |
      {{- $service := include "fluentbit.service" . }}
      {{- if $service }}
        {{- $service | nindent 4 }}
      {{- end }}
      {{- $inputs := include "fluentbit.inputs" . }}
      {{- if $inputs }}
        {{- $inputs | nindent 4 }}
      {{- end }}
      {{- $filters := include "fluentbit.filters" . }}
      {{- if $filters }}
        {{- $filters | nindent 4 }}
      {{- end }}
      {{- $outputs := include "fluentbit.outputs" . }}
      {{- if $outputs }}
        {{- $outputs | nindent 4 }}
      {{- end }}
{{- end }}
