{{- if .Values.fluentbit.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.fluentbit.serviceAccount.name | default "fluentbit-system" }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "operator.labels" . | nindent 4 }}
  annotations:
    {{- include "global.serviceAccountAnnotations" . | nindent 4 }}
    {{- with .Values.fluentbit.serviceAccount.annotations }}
    {{- tpl (toYaml .) $ | nindent 4 }}
    {{- end }}
{{- end }}
