{{- if .Values.fluentbit.enabled }}
{{- if not (include "useCommonServiceAccount" .) }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "fluentbit.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "operator.labels" . | nindent 4 }}
  annotations:
    {{- include "global.serviceAccountAnnotations" . | nindent 4 }}
    {{- with .Values.fluentbit.serviceAccount.annotations }}
    {{- tpl (toYaml .) $ | nindent 4 }}
    {{- end }}
{{- end }}
{{- end }}
