serving:
  auth:
    enabled: false

ingress:
  enabled: true
  dataproxy:
    class: "" # ingress class for managing dataproxy ingress
    hostOverride: "" # If using local control plane installation and routing the dataplane through ingress this could be ingress-nginx-internal.ingress-nginx.svc.cluster.local
  serving:
    class: "" # ingress class for managing serving ingress

secrets:
  admin:
    enable: false
    create: false

config:
  union:
    auth:
      enable: false
  operator:
    enableTunnelService: false
    billableUsageCollector:
      enabled: false

operator:
  enableTunnelService: false

clusterresourcesync:
  config:
    union:
      auth:
        enable: false

