# Use this values file to install Union Dataplane (V2-only) into a cluster where Flyte V1 OSS is also installed. Both can share the same namespace.
# Use it like helm upgrade --install unionai-dataplane unionai/dataplane \
#    --create-namespace \
#    --namespace union \
#    --values values-v2-and-v1.yaml \
#    --values <YOUR_VALUES_FILE>

flytepropeller:
  enabled: false

namespaces:
  enabled: false

clusterresourcesync:
  config:
    cluster_resources:
      customData: {}
  templates: {}