# Use this values file to install Union Dataplane into a single namespace where Flyte V1 OSS is also installed.
# Use it like helm upgrade --install unionai-dataplane unionai/dataplane \
#    --create-namespace \
#    --namespace union \
#    --values values-v2-and-v1.yaml \
#    --values <YOUR_VALUES_FILE>

flytepropeller:
  enabled: false

namespaces:
  enabled: false

clusterresourcesync:
  config:
    cluster_resources:
      customData: {}
  templates: {}