{{- if .Values.flyte.datacatalog.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "datacatalog.configMapName" . }}
  namespace: {{ template "flyte.namespace" . }}
  labels: {{ include "datacatalog.labels" . | nindent 4 }}
data:
{{- with .Values.flyte.db.datacatalog }}
  db.yaml: | {{ tpl (toYaml .) $ | nindent 4 }}
{{- end }}
{{- with .Values.flyte.configmap.otel }}
  otel.yaml: | {{ tpl (toYaml .) $ | nindent 4 }}
{{- end }}
{{- with .Values.flyte.configmap.logger }}
  logger.yaml: | {{ tpl (toYaml .) $ | nindent 4 }}
{{- end }}
{{- with .Values.flyte.configmap.datacatalogServer }}
  server.yaml: | {{ tpl (toYaml .) $ | nindent 4 }}
{{- end }}
{{- if not .Values.flyte.storage.secretName }}
  storage.yaml: | {{ tpl (include "storage" .) $ | nindent 4 }}
{{- end }}
{{- end }}
