{{- if .Values.flyte.datacatalog.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "datacatalog.name" . }}
  namespace: {{ template "flyte.namespace" . }}
  labels: {{ include "datacatalog.labels" . | nindent 4 }}
  {{- with .Values.flyte.datacatalog.service.annotations }}
  annotations: {{ tpl (toYaml .) $ | nindent 4 }}
  {{- end }}
spec:
  {{- with .Values.flyte.datacatalog.service.type}}
  type: {{ . }}
  {{- end }}
  {{- with .Values.flyte.datacatalog.service.clusterIP}}
  clusterIP: {{ . }}
  {{- end }}
  ports:
    - name: http-metrics
      protocol: TCP
      port: {{ index .Values.flyte.configmap.datacatalogServer.datacatalog "profiler-port" }}
    - name: grpc
      port: 89
      protocol: TCP
      targetPort: {{ .Values.flyte.configmap.datacatalogServer.application.grpcPort }}
  {{- with .Values.flyte.datacatalog.service.additionalPorts -}}
  {{ tpl (toYaml .) $ | nindent 2 }}
  {{- end }}
  selector: {{ include "datacatalog.selectorLabels" . | nindent 4 }}
{{- end }}
