{{- if .Values.flytepropellerwebhook.enabled }}
# Webhook deployment
# Create the actual deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "flyte-pod-webhook.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "flytepropellerwebhook.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.flytepropellerwebhook.replicaCount }}
  selector:
    matchLabels:
      {{- include "flytepropellerwebhook.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        platform.union.ai/zone: "dataplane"
        {{- include "flytepropellerwebhook.podLabels" . | nindent 8 }}
      annotations:
        configChecksum: {{ printf "%s%s" (include (print .Template.BasePath "/propeller/configmap.yaml") .) (include (print .Template.BasePath "/leaseworker/configmap.yaml") .) | sha256sum | trunc 63 | quote }}
        {{- with .Values.flytepropellerwebhook.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- include "global.podAnnotations" . | nindent 8 }}
    spec:
      {{- with .Values.flytepropellerwebhook.securityContext }}
      securityContext:
        {{- tpl (toYaml .) $ | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "webhook.serviceAccountName" . }}
      {{- if .Values.flytepropellerwebhook.priorityClassName }}
      priorityClassName: {{ .Values.flytepropellerwebhook.priorityClassName }}
      {{- end }}
      {{- if eq .Values.flytepropellerwebhook.certificate.provider "legacy" }}
      initContainers:
        - name: generate-secrets
          image: "{{ .Values.image.union.repository }}:{{ .Values.image.union.tag | default .Chart.AppVersion }}"
          imagePullPolicy: "{{ .Values.image.union.pullPolicy }}"
          command:
            - flytepropeller
          args:
            - webhook
            - init-certs
            - --config
            - /etc/flyte/config/*.yaml
          env:
            {{- include "global.podEnvVars" . | nindent 12 }}
            {{- with .Values.flytepropellerwebhook.podEnv -}}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          volumeMounts:
            - name: config-volume
              mountPath: /etc/flyte/config
          {{- with .Values.flytepropellerwebhook.resources }}
          resources: {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- end }}
      containers:
        - name: webhook
          image: "{{ .Values.image.union.repository }}:{{ .Values.image.union.tag | default .Chart.AppVersion }}"
          imagePullPolicy: "{{ .Values.image.union.pullPolicy }}"
          command:
            - flytepropeller
          args:
            - webhook
            - --config
            - /etc/flyte/config/*.yaml
          env:
            {{- include "global.podEnvVars" . | nindent 10 }}
            {{- if .Values.flytepropellerwebhook.podEnv -}}
            {{- with .Values.flytepropellerwebhook.podEnv -}}
            {{- toYaml . | nindent 10 }}
            {{- end }}
            {{- end }}
          ports:
            - containerPort: {{ .Values.flytepropellerwebhook.service.targetPort }}
            - containerPort: {{ index .Values.config.core.propeller "prof-port" }}
          {{- with .Values.flytepropellerwebhook.resources }}
          resources: {{- toYaml . | nindent 12 }}
          {{- end }}
          volumeMounts:
            - name: config-volume
              mountPath: /etc/flyte/config
              readOnly: true
            - name: webhook-certs
              mountPath: /etc/webhook/certs
              readOnly: true
          {{- with .Values.flytepropellerwebhook.additionalVolumeMounts -}}
          {{ tpl (toYaml .) $ | nindent 12 }}
          {{- end }}
      volumes:
        - name: config-volume
          {{- if .Values.leaseworker.enabled }}
          projected:
            sources:
              - configMap:
                  name: union-flytepropeller-config
                  items:
                    {{- if .Values.config.admin }}
                    - key: admin.yaml
                      path: admin.yaml
                    {{- end }}
                    {{- if .Values.config.catalog }}
                    - key: catalog.yaml
                      path: catalog.yaml
                    {{- end }}
                    {{- if .Values.config.catalog_cache }}
                    - key: catalog_cache.yaml
                      path: catalog_cache.yaml
                    {{- end }}
                    {{- if .Values.config.copilot }}
                    - key: copilot.yaml
                      path: copilot.yaml
                    {{- end }}
                    - key: core.yaml
                      path: core.yaml
                    - key: k8s.yaml
                      path: k8s.yaml
                    {{- if .Values.logging }}
                    - key: logger.yaml
                      path: logger.yaml
                    {{- end }}
                    {{- if .Values.config.qubole }}
                    - key: qubole.yaml
                      path: qubole.yaml
                    {{- end }}
                    {{- if or .Values.config.namespace_config (include "singleNamespace" .) (and (not .Values.config.namespace_config) .Values.namespace_mapping) }}
                    - key: namespace_config.yaml
                      path: namespace_config.yaml
                    {{- end }}
                    {{- if .Values.config.resource_manager }}
                    - key: resource_manager.yaml
                      path: resource_manager.yaml
                    {{- end }}
                    {{- if and .Values.sparkoperator.enabled .Values.sparkoperator.plugin_config }}
                    - key: spark.yaml
                      path: spark.yaml
                    {{- end }}
                    {{- if and .Values.databricks.enabled .Values.databricks.plugin_config }}
                    - key: databricks.yaml
                      path: databricks.yaml
                    {{- end }}
                    {{- if and .Values.flyteagent.enabled .Values.flyteagent.plugin_config }}
                    - key: agent_service.yaml
                      path: agent_service.yaml
                    {{- end }}
                    - key: storage.yaml
                      path: storage.yaml
              - configMap:
                  name: leaseworker
          {{- else }}
          configMap:
            name: union-flytepropeller-config
          {{- end }}
        - name: webhook-certs
          secret:
            secretName: {{ include "flytepropellerwebhook.secretName" . }}
      {{- with .Values.flytepropellerwebhook.additionalVolumes -}}
      {{ tpl (toYaml .) $ | nindent 8 }}
      {{- end }}
      {{- include "flytepropellerwebhook.scheduling" . | nindent 6 }}
      {{- include "additionalPodSpec" . | nindent 6 }}
{{- end }}
