{{- if .Values.flyteconnector.enabled }}
---
{{- if and .Values.flyteconnector.serviceAccount.create (not (include "useCommonServiceAccount" .)) }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "flyteconnector.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels: {{ include "flyteconnector.labels" . | nindent 4 }}
  {{- with include "flyteconnector.serviceAccount.annotations" . }}
  annotations:
    {{- . | nindent 4 }}
  {{- end}}
  {{- with .Values.flyteconnector.serviceAccount.imagePullSecrets }}
imagePullSecrets: {{ tpl (toYaml .) $ | nindent 2 }}
  {{- end }}
{{- end }}
{{- end }}