{{- if and .Values.dataproxy.enabled .Values.dataproxy.serviceAccount.create }}
{{- if not (include "useCommonServiceAccount" .) }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "dataproxy.serviceAccountName" . }}
  labels:
    {{- include "dataproxy.labels" . | nindent 4 }}
  {{- with include "dataproxy.serviceAccount.annotations" . }}
  annotations:
    {{- . | nindent 4 }}
  {{- end }}
{{- end }}
{{- end }}
