{{- if .Values.flyte.cacheservice.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: cacheservice-config
  namespace: {{ template "flyte.namespace" . }}
  labels: {{ include "cacheservice.labels" . | nindent 4 }}
data:
{{- with .Values.flyte.db.cacheservice }}
  db.yaml: | {{ tpl (toYaml .) $ | nindent 4 }}
{{- end }}
{{- with .Values.flyte.configmap.logger }}
  logger.yaml: | {{ tpl (toYaml .) $ | nindent 4 }}
{{- end }}
{{- with .Values.flyte.configmap.cacheserviceServer }}
  server.yaml: | {{ tpl (toYaml .) $ | nindent 4 }}
{{- end }}
  storage.yaml: | {{ tpl (include "cacheservice-storage" .) $ | nindent 4 }}
{{- end }}
