{{- if and .Values.flyte.useDirectTemplates .Values.flyte.flyteadmin.autoscaling.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ template "flyteadmin.name" . }}
  namespace: {{ template "flyte.namespace" . }}
  labels: {{ include "flyteadmin.labels" . | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ template "flyteadmin.name" . }}
  minReplicas: {{ .Values.flyte.flyteadmin.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.flyte.flyteadmin.autoscaling.maxReplicas }}
  metrics:
    {{ .Values.flyte.flyteadmin.autoscaling.metrics | toYaml | nindent 4 }}
{{- end }}
