{{- if .Values.flyte.useDirectTemplates }}
{{- if not (empty .Values.flyte.secrets.adminOauthClientCredentials.clientSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.flyte.secrets.adminOauthClientCredentials.secretName }}
  namespace: {{ template "flyte.namespace" . }}
type: Opaque
stringData:
  {{- with .Values.flyte.secrets.adminOauthClientCredentials.clientSecret }}
  client_secret: {{  tpl (toYaml .) $ }}
  {{- end }}
{{- end }}
{{- end }}
