apiVersion: gateway.envoyproxy.io/v1alpha1
kind: BackendTrafficPolicy
metadata:
  name: flyteadmin-h2c
  namespace: {{ .Values.clusterGatewayConfig.controlplaneNamespace }}
spec:
  targetRefs:
    - group: ""
      kind: Service
      name: flyteadmin
  http2: {}
