{{- if .Values.serving.enabled }}
apiVersion: operator.knative.dev/v1beta1
kind: KnativeServing
metadata:
  name: {{ include "serving.fullname" . }}
  namespace: {{ .Release.Namespace }}
spec:
  config:
    deployment:
      progress-deadline: "30m"
      queue-sidecar-cpu-request: "25m"
      queue-sidecar-cpu-limit: "1000m"
      queue-sidecar-memory-request: "400Mi"
      queue-sidecar-memory-limit: "800Mi"
      queue-sidecar-ephemeral-storage-request: "512Mi"
      queue-sidecar-ephemeral-storage-limit: "1024Mi"
      {{- if .Values.serving.extraConfig.deployment }}
      {{- tpl (.Values.serving.extraConfig.deployment | toYaml) . | nindent 6 }}
      {{- end }}
    features:
      kubernetes.podspec-affinity: "enabled"
      kubernetes.podspec-nodeselector: "enabled"
      kubernetes.podspec-tolerations: "enabled"
      kubernetes.podspec-fieldref: "enabled"
      {{- if .Values.serving.extraConfig.features }}
      {{- tpl (.Values.serving.extraConfig.features | toYaml) . | nindent 6 }}
      {{- end }}
    network:
      ingress-class: "kourier.ingress.networking.knative.dev"
      {{- if .Values.serving.extraConfig.network }}
      {{- tpl (.Values.serving.extraConfig.network | toYaml) . | nindent 6 }}
      {{- end }}
  high-availability:
    replicas: {{ .Values.serving.replicas }}
  ingress:
    kourier:
      enabled: true
      bootstrap-configmap: "{{ include "serving.envoyBootstrapConfigMapName" . }}"
      service-type: ClusterIP
  podDisruptionBudgets:
  - name: 3scale-kourier-gateway-pdb
    minAvailable: 50%
  - name: activator-pdb
    minAvailable: 50%
  - name: webhook-pdb
    minAvailable: 50%
  registry:
    override:
      # TODO(jeev): Wire up Union fork of Envoy
      3scale-kourier-gateway/kourier-gateway: ghcr.io/unionai/envoy:456fed84d4ad9a9dfb186d117d9362e9dc0f7c1f
      # TODO(jeev): Wire up Union fork of Kourier
      net-kourier-controller/controller: ghcr.io/unionai/kourier@sha256:5804c348d15b3959604e3e3ceed216c3a1c7b32cbe254c7d3eb02a35e62ba9c4
  workloads:
  - name: 3scale-kourier-gateway
    affinity:
      podAntiAffinity:
        preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 100
          podAffinityTerm:
            labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - 3scale-kourier-gateway
            topologyKey: topology.kubernetes.io/zone
    annotations:
      checksum/bootstrap-config: {{ include (print $.Template.BasePath "/serving/bootstrap-configmap.yaml") . | sha256sum }}
    env:
    - container: kourier-gateway
      envVars:
      - name: UNION_AUTHZ_TENANTAUTHURL
        value: "https://{{ .Values.host }}/me"
      - name: UNION_AUTHZ_TENANTAUTHSIGNINURL
        value: "https://{{ .Values.host }}/login"
      - name: UNION_AUTHZ_TENANTCONTROLPLANEURL
        value: "https://{{ .Values.host }}"
    {{- with index .Values.serving.resources "3scale-kourier-gateway" }}
    resources:
    {{- range $container, $resources := . }}
      - container: {{ $container }}
        {{- $resources | toYaml | nindent 8 }}
    {{- end }}
    {{- end }}
  - name: activator
    affinity:
      podAntiAffinity:
        preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 100
          podAffinityTerm:
            labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - activator
            topologyKey: topology.kubernetes.io/zone
  - name: autoscaler
    affinity:
      podAntiAffinity:
        preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 100
          podAffinityTerm:
            labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - autoscaler
            topologyKey: topology.kubernetes.io/zone
  - name: autoscaler-hpa
    affinity:
      podAntiAffinity:
        preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 100
          podAffinityTerm:
            labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - autoscaler-hpa
            topologyKey: topology.kubernetes.io/zone
  - name: controller
    affinity:
      podAntiAffinity:
        preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 100
          podAffinityTerm:
            labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - controller
            topologyKey: topology.kubernetes.io/zone
  - name: net-kourier-controller
    affinity:
      podAntiAffinity:
        preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 100
          podAffinityTerm:
            labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - net-kourier-controller
            topologyKey: topology.kubernetes.io/zone
    env:
    - container: controller
      envVars:
      - name: KOURIER_UNION_AUTHZ_ENABLED
        value: "true"
    {{- with index .Values.serving.resources "net-kourier-controller" }}
    resources:
    {{- range $container, $resources := . }}
      - container: {{ $container }}
        {{- $resources | toYaml | nindent 8 }}
    {{- end }}
    {{- end }}
  - name: webhook
    affinity:
      podAntiAffinity:
        preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 100
          podAffinityTerm:
            labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - webhook
            topologyKey: topology.kubernetes.io/zone
{{- end }}
