{{- if and .Values.serving.enabled .Values.serving.openShift.kourierGatewayScc.enabled }}
{{- include "openshift.sccRbac" (dict "root" . "name" (include "serving.kourierGateway.openShiftSccName" .) "labels" (include "serving.labels" .) "serviceAccountName" .Values.serving.openShift.kourierGatewayScc.serviceAccountName) }}
{{- end }}
