{{- if and .Values.serving.enabled .Values.serving.openShift.kourierGatewayScc.enabled .Values.serving.openShift.kourierGatewayScc.create }}
apiVersion: security.openshift.io/v1
kind: SecurityContextConstraints
metadata:
  name: {{ include "serving.kourierGateway.openShiftSccName" . }}
  labels:
    {{- include "serving.labels" . | nindent 4 }}
allowHostDirVolumePlugin: false
allowHostIPC: false
allowHostNetwork: false
allowHostPID: false
allowHostPorts: false
allowPrivilegeEscalation: false
allowPrivilegedContainer: false
allowedCapabilities: []
defaultAddCapabilities: []
defaultAllowPrivilegeEscalation: false
forbiddenSysctls:
  - "*"
readOnlyRootFilesystem: false
requiredDropCapabilities:
  - ALL
runAsUser:
  type: MustRunAs
  uid: {{ .Values.serving.openShift.kourierGatewayScc.uid }}
seLinuxContext:
  type: MustRunAs
seccompProfiles:
  - runtime/default
fsGroup:
  type: RunAsAny
supplementalGroups:
  type: RunAsAny
volumes:
  - configMap
  - downwardAPI
  - emptyDir
  - projected
  - secret
{{- end }}
