{{- if .Values.fuseDevicePlugin.enabled }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "unionai-dataplane.fullname" . }}-fuse-device-plugin
  labels:
    {{- include "fuseDevicePlugin.labels" . | nindent 4 }}
data:
  conf.yaml: |
    {{- toYaml .Values.fuseDevicePlugin.devices | nindent 4 }}
{{- end }}
