apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "union-operator.fullname" . }}-prometheus
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "unionai-dataplane.labels" . | nindent 4 }}
    app.kubernetes.io/component: prometheus
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: prometheus
      {{- include "unionai-dataplane.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        configChecksum: {{ include (print .Template.BasePath "/prometheus/configmap.yaml") . | sha256sum | trunc 63 | quote }}
      labels:
        app.kubernetes.io/component: prometheus
        {{- include "unionai-dataplane.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.prometheus.priorityClassName }}
      priorityClassName: {{ . }}
      {{- end }}
      serviceAccountName: {{ include "union-operator.fullname" . }}-prometheus
      securityContext:
        fsGroup: 65534
        runAsNonRoot: true
        runAsUser: 65534
        {{- if ge (int (mustRegexFind "[0-9]+" .Capabilities.KubeVersion.Minor)) 23 }}
        fsGroupChangePolicy: OnRootMismatch
        {{- end }}
      containers:
        - name: prometheus
          image: "{{ .Values.prometheus.image.repository }}:{{ .Values.prometheus.image.tag }}"
          args:
            - --config.file=/etc/prometheus/prometheus.yml
            - --web.external-url={{ .Values.prometheus.routePrefix }}
            - --web.route-prefix={{ .Values.prometheus.routePrefix }}
            - --storage.tsdb.retention.time={{ .Values.prometheus.retention }}
          ports:
            - name: http
              containerPort: 9090
              protocol: TCP
          resources:
            {{- toYaml .Values.prometheus.resources | nindent 12 }}
          securityContext:
            allowPrivilegeEscalation: false
          terminationMessagePolicy: FallbackToLogsOnError
          volumeMounts:
            - mountPath: /etc/prometheus
              name: prometheus-config
      volumes:
        - name: prometheus-config
          configMap:
            name: {{ include "union-operator.fullname" . }}-prometheus
      {{- include "prometheus.scheduling" . | nindent 6 }}
