apiVersion: v1
kind: Service
metadata:
  name: {{ include "union-operator.fullname" . }}-prometheus
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "unionai-dataplane.labels" . | nindent 4 }}
    app.kubernetes.io/component: prometheus
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 9090
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/component: prometheus
    {{- include "unionai-dataplane.selectorLabels" . | nindent 4 }}
