---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: flytepropeller-webhook-role
  namespace: {{ .Release.Namespace }}
rules:
  - apiGroups:
      - "*"
    resources:
      - mutatingwebhookconfigurations
      - secrets
      - pods
      - replicasets/finalizers
    verbs:
      - get
      - create
      - update
      - patch
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: flytepropeller-webhook-system
  namespace: {{ .Release.Namespace }}
  {{- with include "global.serviceAccountAnnotations" . }}
  annotations:
    {{- . | nindent 4 }}
  {{- end }}
{{- with .Values.flytepropellerwebhook.serviceAccount.imagePullSecrets }}
imagePullSecrets: {{ tpl (toYaml .) $ | nindent 2 }}
{{- end }}
---
# Create a binding from Role -> ServiceAccount
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: flytepropeller-webhook-binding
  namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: flytepropeller-webhook-role
subjects:
  - kind: ServiceAccount
    name: flytepropeller-webhook-system
    namespace: {{ .Release.Namespace }}
